config/routes.rb
Rails.application.routes.draw do

	root 'champions#index'
  resources :champions

	namespace 'api' do
		root 'api#index' 
	end

end

app/models/champion.rb
class Champion < ActiveRecord::Base


	def image_url
		'http://ddragon.leagueoflegends.com/cdn/4.2.6/img/champion/' + self.key + '.png'
	end

end

app/controllers/api/api_controller.rb
module Api

	class ApiController < ApplicationController

	def index
		#r = Faraday.get 'http://example.com'

		#@test = RiotApiConnector.test
		riot = RiotApiConnector.new
		riot.load_all_champions
		@test = "asf"
  end


	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  before_action :set_champion, only: [:show, :edit, :update, :destroy]

  # GET /champions
  # GET /champions.json
  def index
    @champions = Champion.all
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
  end

  # GET /champions/new
  def new
    @champion = Champion.new
  end

  # GET /champions/1/edit
  def edit
  end

  # POST /champions
  # POST /champions.json
  def create
    @champion = Champion.new(champion_params)

    respond_to do |format|
      if @champion.save
        format.html { redirect_to @champion, notice: 'Champion was successfully created.' }
        format.json { render :show, status: :created, location: @champion }
      else
        format.html { render :new }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /champions/1
  # PATCH/PUT /champions/1.json
  def update
    respond_to do |format|
      if @champion.update(champion_params)
        format.html { redirect_to @champion, notice: 'Champion was successfully updated.' }
        format.json { render :show, status: :ok, location: @champion }
      else
        format.html { render :edit }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champions/1
  # DELETE /champions/1.json
  def destroy
    @champion.destroy
    respond_to do |format|
      format.html { redirect_to champions_url, notice: 'Champion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_champion
      @champion = Champion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def champion_params
      params.require(:champion).permit(:name, :lore)
    end
end

app/views/champions/_form.html.erb
<%= form_for @champion, :html => { :class => "form-horizontal champion" } do |f| %>

    <% if @champion.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@champion.errors.count, "error") %> prohibited this champion from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @champion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :key, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :key, :class => 'form-control' %>
    </div>
    <%= error_span(@champion[:key]) %>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@champion[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@champion[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :partype, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :partype, :class => 'form-control' %>
    </div>
    <%= error_span(@champion[:partype]) %>
  </div>
  <div class="control-group">
    <%= f.label :lore, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :lore, :class => 'form-control' %>
    </div>
    <%= error_span(@champion[:lore]) %>
  </div>
  <div class="control-group">
    <%= f.label :blurb, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :blurb, :class => 'form-control' %>
    </div>
    <%= error_span(@champion[:blurb]) %>
  </div>

  <div class="control-group control-panel">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), champions_path, :class => 'btn btn-default' %>
  </div>

<% end %>

app/views/champions/edit.html.erb
<%- model_class = Champion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/champions/index.html.erb
<%- model_class = Champion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:key) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:partype) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @champions.each do |champion| %>
      <tr>
        <td><%= link_to champion.id, champion_path(champion) %></td>
        <td><%= champion.key %></td>
        <td><%= champion.name %></td>
        <td><%= champion.title %></td>
        <td><%= champion.partype %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_champion_path(champion), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      champion_path(champion),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_champion_path,
            :class => 'btn btn-primary' %>

app/views/champions/new.html.erb
<%- model_class = Champion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/champions/show.html.erb
<%- model_class = Champion -%>
<div class="page-header" >
  <h1>
    <%= image_tag(@champion.image_url) %>
    <%= @champion.name %>
  </h1>
</div>
<div style="clear:both"></div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @champion.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @champion.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @champion.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:partype) %>:</strong></dt>
  <dd><%= @champion.partype %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lore) %>:</strong></dt>
  <dd><%= @champion.lore %></dd>
  <dt><strong><%= model_class.human_attribute_name(:blurb) %>:</strong></dt>
  <dd><%= @champion.blurb %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              champions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_champion_path(@champion), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              champion_path(@champion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lol Team Maker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Lol Team Maker", root_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Champions", champions_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Lol Team Maker 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>